name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  supabase_flutter: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/operativexD.jpeg
    - assets/images/operativexL.jpg
    - assets/images/bg_light.png
    - assets/images/bg_dark.png